export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_SINGLE_REQUEST = 'PRODUCT_SINGLE_REQUEST';
export const PRODUCT_SINGLE_SUCCESS = 'PRODUCT_SINGLE_SUCCESS';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET';

export const PRODUCT_CATEGORIES_LIST_REQUEST = 'PRODUCT_CATEGORIES_LIST_REQUEST';
export const PRODUCT_CATEGORIES_LIST_SUCCESS = 'PRODUCT_CATEGORIES_LIST_SUCCESS';
export const PRODUCT_CATEGORIES_LIST_FAIL = 'PRODUCT_CATEGORIES_LIST_FAIL';

export const PRODUCT_COMMENT_CREATE_REQUEST = 'PRODUCT_COMMENT_CREATE_REQUEST';
export const PRODUCT_COMMENT_CREATE_SUCCESS = 'PRODUCT_COMMENT_CREATE_SUCCESS';
export const PRODUCT_COMMENT_CREATE_FAIL = 'PRODUCT_COMMENT_CREATE_FAIL';
export const PRODUCT_COMMENT_CREATE_RESET = 'PRODUCT_COMMENT_CREATE_RESET';

export const PRODUCT_TOP_LIST_REQUEST = 'PRODUCT_TOP_LIST_REQUEST';
export const PRODUCT_TOP_LIST_SUCCESS = 'PRODUCT_TOP_LIST_SUCCESS';

export const PRODUCT_TOP_CAROUSEL_REQUEST = 'PRODUCT_TOP_CAROUSEL_REQUEST';
export const PRODUCT_TOP_CAROUSEL_SUCCESS = 'PRODUCT_TOP_CAROUSEL_SUCCESS';